hepsi: derle calistir

derle:
	g++ -I .\include\ -o .\lib\Dugum.o -c .\src\Dugum.cpp
	g++ -I .\include\ -o .\lib\BagliListe.o -c .\src\BagliListe.cpp
	g++ -I .\include\ -o .\bin\program.exe .\lib\Dugum.o .\lib\BagliListe.o .\src\main.cpp

calistir:
	.\bin\program.exe